---
applications:
  - name: spring-ai-workshop
    path: ./ai-workshop-0.0.1-SNAPSHOT.jar
    random-route: true
    env:
      JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 21.+ } }'
    buildpacks:
      - java_buildpack_offline
    services:
      - name: genai-service
